### ISSUE TITLE
The directory src/ip is empty.

### ISSUE THREAD

**Issue by sergei-romanenko** [Digilent/Cora-Z7-10-Pi-Estimator-VGA#1]
It seems that `src/ip` should contain `clk_wiz_0` (and some other ip-cores?). But `src/ip` is empty.

**Comment by jpeyron** [comment]
I have added a release for the Cora-Z7 10 Pi Estimator VGA  using Vivado 2017.4 here: https://github.com/Digilent/Cora-Z7-10-Pi-Estimator-VGA/releases

**Comment by sergei-romanenko** [comment]
Note that in the project
<https://github.com/artvvb/Cora-Z7-10-Pi-Estimator-VGA>
`src/ip` contains the necessary components `clk_wiz_0` and `blk_mem_gen_0`.
It seems that the version in `artvvb` can be just merged into this repository.

**Comment by sergei-romanenko** [comment]
It seems that something is wrong with `Cora-Z7-10-Pi-Estimator-VGA-2017.4-1.zip`.
I've tried to open the project with Vivado 2018.3 and it complains that there is no `blk_mem_gen_0` in `Cora-Z7-10-Pi_Estimator-VGA.srcs/sources_1/ip`.

**Comment by jpeyron** [comment]
I just downloaded the release and completed this project in vivado "2018.3.1". After loading the project into Vivado 2018.3 upgrade the IP's by clicking reports->report ip status and then click upgrade selected.
then generate a bitstream.

**Comment by sergei-romanenko** [comment]
That's right, IP's have to be upgraded. And `clk_wiz_0` IS upgradable. But there is another problem with the xpr-file.

Compare the following lines in the xpr-file:

    <File Path="$PSRCDIR/sources_1/ip/clk_wiz_0/clk_wiz_0.xci">
    <File Path="$PPRDIR/../../../src/ip/blk_mem_gen_0/blk_mem_gen_0.xci">

`blk_mem_gen_0` is not included into the project tree and is supposed to be taken from some place in your computer.

Besides, there is a lot of other lines like

    <File Path="$PPRDIR/../../../src/hdl/PiSimulator_VGA.v">

referencing files outside the project tree.

**Comment by sergei-romanenko** [comment]
OK. Now the necessary stuff has appeared in `src/ip`.
But there have also appeared a few new files in the project: `PiSimulator_VGA.v`, `circleChecker.v`, `pixelMemory.v`. In addition to `pi_estimator_vga.v`, `circle_checker.v`, `pixel_memory.v`!

As a result (?) I get the message:

    [Synth 8-4442] BlackBox module px_mem has unconnected pin web[0]

Maybe some files should be removed?

**Comment by artvvb** [comment]
Resolved with https://github.com/Digilent/Cora-Z7-10-Pi-Estimator-VGA/commit/0f99ee5ff980f1c1806584e34df20c3f56cfd0ea. There were several bugs in how the block memory generator was instantiated.

**Comment by sergei-romanenko** [comment]
I've tried the project with Vivado 2019.1. Now everything seems to be OK.
